### ISSUE TITLE
Panic when using mock provider

### ISSUE THREAD

**Issue by LuBingtan** [virtual-kubelet/virtual-kubelet#1040]
---

### Environment summary

Provider (e.g. ACI, AWS Fargate): mock

Version (e.g. 0.1, 0.2-beta): master(latest)

K8s Master Info (e.g. AKS, ACS, Bare Metal, EKS): Bare Metal

Install Method (e.g. Helm Chart, ): Building from source

### Issue Details
I tried to run virtual kubelet with mock provider, and got erros:
```
WARNING: Package "github.com/golang/protobuf/protoc-gen-go/generator" is deprecated.
	A future release of golang/protobuf will delete this package,
	which has long been excluded from the compatibility promise.

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0xf6aadc]

goroutine 1 [running]:
github.com/virtual-kubelet/virtual-kubelet/node/nodeutil.WebhookAuth(0x0, 0x0, 0xfffffebf3a1c, 0x6, 0x40007d0750, 0x1, 0x1, 0x13a888e, 0x1b, 0xfffffebf39c3, ...)
	/go/src/github.com/virtual-kubelet/virtual-kubelet/node/nodeutil/auth.go:133 +0xbc
github.com/virtual-kubelet/virtual-kubelet/cmd/virtual-kubelet/internal/commands/root.setAuth.func2(0x4000536000, 0x0, 0x0)
	/go/src/github.com/virtual-kubelet/virtual-kubelet/cmd/virtual-kubelet/internal/commands/root/root.go:184 +0x7c
github.com/virtual-kubelet/virtual-kubelet/node/nodeutil.NewNode(0xfffffebf3a1c, 0x6, 0x40007d16b0, 0x40007d16d0, 0x4, 0x4, 0x280a, 0xfffffebf3a1c, 0x6)
	/go/src/github.com/virtual-kubelet/virtual-kubelet/node/nodeutil/controller.go:309 +0x284
github.com/virtual-kubelet/virtual-kubelet/cmd/virtual-kubelet/internal/commands/root.runRootCommand(0x15c81a0, 0x400028ecc0, 0x400039b390, 0xfffffebf39f8, 0x18, 0x0, 0x0, 0x1395756, 0xd, 0x280a, ...)
	/go/src/github.com/virtual-kubelet/virtual-kubelet/cmd/virtual-kubelet/internal/commands/root/root.go:110 +0x2c0
github.com/virtual-kubelet/virtual-kubelet/cmd/virtual-kubelet/internal/commands/root.NewCommand.func1(0x400016c580, 0x4000025f80, 0x0, 0x7, 0x0, 0x0)
	/go/src/github.com/virtual-kubelet/virtual-kubelet/cmd/virtual-kubelet/internal/commands/root/root.go:47 +0x78
github.com/spf13/cobra.(*Command).execute(0x400016c580, 0x40000bc010, 0x7, 0x7, 0x400016c580, 0x40000bc010)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x30c
github.com/spf13/cobra.(*Command).ExecuteC(0x400016c580, 0x400039b430, 0x1390bfa, 0x9)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x268
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
	/go/src/github.com/virtual-kubelet/virtual-kubelet/cmd/virtual-kubelet/main.go:91 +0x51c
```

### Repro steps
Provider config (mock_config.json):
```json
{
	"mynode": {
		"cpu":"1",
		"memory":"1Gi",
		"pods": "10"
	}
}
```

Set environment variables:
```bash
export APISERVER_CA_CERT_LOCATION=/etc/ssl/kubernetes/server/ca.crt
export APISERVER_CERT_LOCATION=/etc/ssl/kubernetes/server/tls.crt
export APISERVER_KEY_LOCATION=/etc/ssl/kubernetes/server/tls.key
export KUBECONFIG=/var/lib/kube/kubeconfig
```

Command:
```bash
virtual-kubelet --provider mock \
  --provider-config mock_config.json \
  --kubeconfig /var/lib/kube/kubeconfig \
  --nodename=mynode
```

**Comment by LuBingtan** [comment]
It seems that the root case is [here](https://github.com/virtual-kubelet/virtual-kubelet/blob/master/node/nodeutil/controller.go#L309). The `cfg.Client`  is used by `opts` func before initialization.

https://github.com/virtual-kubelet/virtual-kubelet/blob/fca742986c0f15929226b21ddbaf1b1ce58ba0f2/node/nodeutil/controller.go#L309-L325

**Comment by cpuguy83** [comment]
Yeah.... I think we can do something like pre-initialize a default client before options are run.
Did you want to make a PR for that?

**Comment by LuBingtan** [comment]
> Yeah.... I think we can do something like pre-initialize a default client before options are run. Did you want to make a PR for that?

yes, I'd like to make a PR

**Comment by LuBingtan** [comment]
@cpuguy83 
Hi, I opened this PR https://github.com/virtual-kubelet/virtual-kubelet/pull/1043
PTAL
