### ISSUE TITLE
Segfault when running mock provider and not supplying KUBECONFIG environment variable

### ISSUE THREAD

**Issue by xelxebar** [virtual-kubelet/virtual-kubelet#1088]
### Overview

When running `virtual-kubelet` without `KUBECONFIG` in the environment, a panic ensues:

```
$ APISERVER_CERT_LOCATION=~/.minikube/profiles/minikube/apiserver.crt APISERVER_KEY_LOCATION=~/.minikube/profiles/minikube/apiserver.key APISERVER_CA_CERT_LOCATION=~/.minikube/ca.crt ./virtual-kubelet --provider mock
WARN[0000] Failed to create clientset from env. Ignore this error If you use your own client  error="error getting rest client config: unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x1479f00]

goroutine 1 [running]:
k8s.io/client-go/kubernetes.(*Clientset).AuthenticationV1(0xc00021f3b0?)
        /home/x/go/pkg/mod/k8s.io/client-go@v0.25.0/kubernetes/clientset.go:210
github.com/virtual-kubelet/virtual-kubelet/node/nodeutil.WebhookAuth({0x1e4d150, 0x0}, {0x1bbaf76, 0xf}, {0xc000832c88, 0x1, 0x4?})
        /home/x/devel/com.github/virtual-kubelet/virtual-kubelet/node/nodeutil/auth.go:133 +0xff
github.com/virtual-kubelet/virtual-kubelet/cmd/virtual-kubelet/internal/commands/root.setAuth.func2(0xc00020aa80)
        /home/x/devel/com.github/virtual-kubelet/virtual-kubelet/cmd/virtual-kubelet/internal/commands/root/root.go:184 +0x70
github.com/virtual-kubelet/virtual-kubelet/node/nodeutil.NewNode({0x1bbaf76, 0xf}, 0xc000833878, {0xc000833898, 0x4, 0xd?})
        /home/x/devel/com.github/virtual-kubelet/virtual-kubelet/node/nodeutil/controller.go:312 +0x342
github.com/virtual-kubelet/virtual-kubelet/cmd/virtual-kubelet/internal/commands/root.runRootCommand({_, _}, _, {{0xc0000582b8, 0x14}, {0x0, 0x0}, {0x1bb7dc1, 0xd}, 0x280a, ...})
        /home/x/devel/com.github/virtual-kubelet/virtual-kubelet/cmd/virtual-kubelet/internal/commands/root/root.go:110 +0x397
github.com/virtual-kubelet/virtual-kubelet/cmd/virtual-kubelet/internal/commands/root.NewCommand.func1(0xc000436280?, {0xc0000b0660?, 0x2?, 0x2?})
        /home/x/devel/com.github/virtual-kubelet/virtual-kubelet/cmd/virtual-kubelet/internal/commands/root/root.go:47 +0x58
github.com/spf13/cobra.(*Command).execute(0xc000436280, {0xc0000500a0, 0x2, 0x2})
        /home/x/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:872 +0x694
github.com/spf13/cobra.(*Command).ExecuteC(0xc000436280)
        /home/x/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /home/x/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
main.main()
        /home/x/devel/com.github/virtual-kubelet/virtual-kubelet/cmd/virtual-kubelet/main.go:91 +0x5d0
```

Setting `KUBECONFIG=~/.kube/config` averts the segfault.

### Environment summary

Built using the tip of `master`:

```
$ git rev-parse HEAD
a90f71b9a4061614c933ead78e8e53df305e399b
```

### Code Investigation

From what I can tell, the `nil` is getting generated here:
https://github.com/virtual-kubelet/virtual-kubelet/blob/a90f71b9a4061614c933ead78e8e53df305e399b/node/nodeutil/auth.go#L136
Apparently, `WebhookAuthConfig.AuthnConfig` is returning `nil` for some reason, *and* the clientset code really doesn't handle that well.

**Comment by lbzss** [comment]
@helayoty, I wanna try to fix it, can you assign the issue to me?

**Comment by helayoty** [comment]
@lbzss, sure!

**Comment by lbzss** [comment]
@helayoty, seems the issue has been fixed in #1085. The issue can be closed.
