### ISSUE TITLE
Failed to make test on AliCloud ECS

### ISSUE THREAD

**Issue by lioncruise** [virtual-kubelet/virtual-kubelet#142]
---

### Environment summary

Provider: AliCloud ECS

Version: latest version

Error occurred while make test.

### Issue Details

```bash
~ go get github.com/virtual-kubelet/virtual-kubelet
~ cd /root/go/src/github.com/virtual-kubelet/virtual-kubelet/
virtual-kubelet git:(master) make test
Testing...
Testing Outside CI...
?   	github.com/virtual-kubelet/virtual-kubelet	[no test files]
?   	github.com/virtual-kubelet/virtual-kubelet/cmd	[no test files]
ok  	github.com/virtual-kubelet/virtual-kubelet/manager	0.081s
?   	github.com/virtual-kubelet/virtual-kubelet/providers	[no test files]
ok  	github.com/virtual-kubelet/virtual-kubelet/providers/azure	0.082s
?   	github.com/virtual-kubelet/virtual-kubelet/providers/azure/client	[no test files]
2018/04/18 19:08:51 Failed to load Azure authentication file: Reading authentication file "../../../../credentials.json" failed: open ../../../../credentials.json: no such file or directory
FAIL	github.com/virtual-kubelet/virtual-kubelet/providers/azure/client/aci	0.012s
ok  	github.com/virtual-kubelet/virtual-kubelet/providers/azure/client/api	0.023s
--- FAIL: TestNewClient (0.00s)
	client_test.go:25: Failed to load Azure authentication file: Reading authentication file "../../../../credentials.json" failed: open ../../../../credentials.json: no such file or directory
--- FAIL: TestResourceGroupDoesNotExist (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x6f0fc6]

goroutine 20 [running]:
testing.tRunner.func1(0xc4201101e0)
	/usr/lib/golang/src/testing/testing.go:711 +0x2d2
panic(0x74ab60, 0x980280)
	/usr/lib/golang/src/runtime/panic.go:491 +0x283
github.com/virtual-kubelet/virtual-kubelet/providers/azure/client/resourcegroups.(*Client).ResourceGroupExists(0x0, 0xc4200ae1e0, 0x1c, 0x2d1d1500, 0x0, 0x0)
	/root/go/src/github.com/virtual-kubelet/virtual-kubelet/providers/azure/client/resourcegroups/exists.go:30 +0x2f6
github.com/virtual-kubelet/virtual-kubelet/providers/azure/client/resourcegroups.TestResourceGroupDoesNotExist(0xc4201101e0)
	/root/go/src/github.com/virtual-kubelet/virtual-kubelet/providers/azure/client/resourcegroups/client_test.go:37 +0x49
testing.tRunner(0xc4201101e0, 0x7becd0)
	/usr/lib/golang/src/testing/testing.go:746 +0xd0
created by testing.(*T).Run
	/usr/lib/golang/src/testing/testing.go:789 +0x2de
FAIL	github.com/virtual-kubelet/virtual-kubelet/providers/azure/client/resourcegroups	0.007s
?   	github.com/virtual-kubelet/virtual-kubelet/providers/hypersh	[no test files]
?   	github.com/virtual-kubelet/virtual-kubelet/providers/mock	[no test files]
?   	github.com/virtual-kubelet/virtual-kubelet/providers/web	[no test files]
?   	github.com/virtual-kubelet/virtual-kubelet/version	[no test files]
?   	github.com/virtual-kubelet/virtual-kubelet/vkubelet	[no test files]
make: *** [test] Error 1
```

**Comment by robbiezhang** [comment]
This is expected since you didn't setup the Azure credentials locally.
https://github.com/virtual-kubelet/virtual-kubelet/blob/master/providers/azure/client/README.md

You can ignore them if you didn't change the Azure provider.
