### ISSUE TITLE
virtual-kubelet crashes when connecting to an existing Kubernetes cluster

### ISSUE THREAD

**Issue by prateekgogia** [virtual-kubelet/virtual-kubelet#20]
As soon as I start virtual-kubelet, it crashes with the traces below.
Cluster is not having any daemonset applications. My guess is K8S is trying to schedule kube-proxy and networking components to the virtual-kubelet. Is there any plan on how to support kube-proxy scheduling ?

Kubernetes version:
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.3", GitCommit:"2c2fe6e8278a5db2d15a013987b53968c743f2a1", GitTreeState:"clean", BuildDate:"2017-08-03T07:00:21Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.1", GitCommit:"f38e43b221d08850172a9a4ea785a86a3ffa3b3a", GitTreeState:"clean", BuildDate:"2017-10-11T23:16:41Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

```
./virtual-kubelet --provider azure
/Users/pgogia/.kube/config
2017/12/11 18:46:28 Node 'virtual-kubelet' with OS type 'Linux' registered

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x1acc27e]

goroutine 1 [running]:
github.com/virtual-kubelet/virtual-kubelet/providers/azure.(*ACIProvider).getVolumes(0xc420328080, 0xc420208a80, 0x253a9b0, 0x0, 0x0, 0x0, 0x0)
	/Users/pgogia/workspace/golang/src/github.com/virtual-kubelet/virtual-kubelet/providers/azure/aci.go:475 +0x20e
github.com/virtual-kubelet/virtual-kubelet/providers/azure.(*ACIProvider).CreatePod(0xc420328080, 0xc420208a80, 0x0, 0x0)
	/Users/pgogia/workspace/golang/src/github.com/virtual-kubelet/virtual-kubelet/providers/azure/aci.go:115 +0x1e3
github.com/virtual-kubelet/virtual-kubelet/vkubelet.(*Server).createPod(0xc420386ea0, 0xc420208a80, 0xb, 0xc4202ab260)
	/Users/pgogia/workspace/golang/src/github.com/virtual-kubelet/virtual-kubelet/vkubelet/vkubelet.go:274 +0x7c
github.com/virtual-kubelet/virtual-kubelet/vkubelet.(*Server).reconcile(0xc420386ea0)
	/Users/pgogia/workspace/golang/src/github.com/virtual-kubelet/virtual-kubelet/vkubelet/vkubelet.go:251 +0x347
github.com/virtual-kubelet/virtual-kubelet/vkubelet.(*Server).Run(0xc420386ea0, 0xf, 0x1d6d8cf)
	/Users/pgogia/workspace/golang/src/github.com/virtual-kubelet/virtual-kubelet/vkubelet/vkubelet.go:170 +0x32d
github.com/virtual-kubelet/virtual-kubelet/cmd.glob..func1(0x2513680, 0xc4201c1a80, 0x0, 0x2)
	/Users/pgogia/workspace/golang/src/github.com/virtual-kubelet/virtual-kubelet/cmd/root.go:54 +0x1cd
github.com/virtual-kubelet/virtual-kubelet/vendor/github.com/spf13/cobra.(*Command).execute(0x2513680, 0xc4200740a0, 0x2, 0x2, 0x2513680, 0xc4200740a0)
	/Users/pgogia/workspace/golang/src/github.com/virtual-kubelet/virtual-kubelet/vendor/github.com/spf13/cobra/command.go:702 +0x2bd
github.com/virtual-kubelet/virtual-kubelet/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x2513680, 0x10067a4, 0xc42006e058, 0x0)
	/Users/pgogia/workspace/golang/src/github.com/virtual-kubelet/virtual-kubelet/vendor/github.com/spf13/cobra/command.go:783 +0x349
github.com/virtual-kubelet/virtual-kubelet/vendor/github.com/spf13/cobra.(*Command).Execute(0x2513680, 0x0, 0x0)
	/Users/pgogia/workspace/golang/src/github.com/virtual-kubelet/virtual-kubelet/vendor/github.com/spf13/cobra/command.go:736 +0x2b
github.com/virtual-kubelet/virtual-kubelet/cmd.Execute()
	/Users/pgogia/workspace/golang/src/github.com/virtual-kubelet/virtual-kubelet/cmd/root.go:61 +0x31
main.main()
	/Users/pgogia/workspace/golang/src/github.com/virtual-kubelet/virtual-kubelet/main.go:20 +0x20
```

**Comment by erikstmartin** [comment]
This happens when you have a daemonset in the cluster? Does it occur when there isn't a daemonset?

**Comment by erikstmartin** [comment]
There may still be something with daemonsets, but the taint on the virtual-kubelet should prevent daemonsets from running on it. I checked the code that was throwing the nil pointer exception and did find a copy/paste error with ConfigMap volumes. I've pushed a fix for that, it likely will fix this crash you're seeing.

Please let me know either way.

**Comment by prateekgogia** [comment]
Thanks for the response. I created a new Kubernetes cluster, at this point no user applications are running. Following are the pods running - 

```
kubectl get pods -o wide -a --all-namespaces
NAMESPACE     NAME                            READY     STATUS    RESTARTS   AGE       IP             NODE
kube-system   etcd-node1                      1/1       Running   0          3m        10.150.11.11   node1
kube-system   kube-apiserver-node1            1/1       Running   0          3m        10.150.11.11   node1
kube-system   kube-controller-manager-node1   1/1       Running   0          3m        10.150.11.11   node1
kube-system   kube-dns-545bc4bfd4-lzn4b       3/3       Running   0          4m        10.244.0.93    node1
kube-system   kube-flannel-ds-gj9wk           1/1       Running   0          36s       10.150.11.11   node1
kube-system   kube-proxy-fx99z                1/1       Running   0          4m        10.150.11.11   node1
kube-system   kube-scheduler-node1            1/1       Running   0          4m        10.150.11.11   node1
```

I added a log to capture more details in virtual-kubelet code, it was crashing because the kube-proxy gets scheduled as soon it connects.
I also verified your fix, the crash is gone. However, kube-proxy scheduling won't work. This will require using taints to not schedule kube-proxy on virtual-kubelet. This is the log I am currently getting -
```
./virtual-kubelet --provider azure
/Users/pgogia/.kube/config
2017/12/12 16:39:23 Node 'virtual-kubelet' with OS type 'Linux' registered
2017/12/12 16:39:24 Error creating pod 'kube-proxy-z5rh7': Pod kube-proxy-z5rh7 requires volume xtables-lock which is of an unsupported type
2017/12/12 16:39:26 Error creating pod 'kube-proxy-8dzks': Pod kube-proxy-8dzks requires volume xtables-lock which is of an unsupported type
2017/12/12 16:39:27 Error creating pod 'kube-proxy-4k2dx': Pod kube-proxy-4k2dx requires volume xtables-lock which is of an unsupported type
2017/12/12 16:39:28 Error creating pod 'kube-proxy-5pbng': Pod kube-proxy-5pbng requires volume xtables-lock which is of an unsupported type
2017/12/12 16:39:30 Error creating pod 'kube-proxy-z2k2g': Pod kube-proxy-z2k2g requires volume xtables-lock which is of an unsupported type

```

**Comment by resouer** [comment]
@erikstmartin I also noticed there's DS scheduled to virtual-kubelet. What's the policy of what we allow/disallow running on virtual-kubelet?

**Comment by prateekgogia** [comment]
@erikstmartin @resouer Will it be fair to consider that the workloads/pods which will be running on the virtual-kubelet(s) are special pods. As a user I know the specific pods which I want to run on the virtual-kubelet backends and I can add tolerations to these workloads, or there can be a custom admission controller, which can add these tolerations. 

When virtual-kubelet is run, it can have a `register-with-taints` option, so not everything like kube-proxy gets scheduled on the virtual-kubelet. This way specific pods can only be scheduled on the virtual-kubelet with matching taints ?

**Comment by prateekgogia** [comment]
Sorry, just saw `--taint` is supported already in virtual-kubelet. So, now it just needs documentation on how to use it to avoid scheduling `kube-proxy` pods on this node and add tolerations to pods / workloads which are supposed to be scheduled on virtual-kubelet.

**Comment by resouer** [comment]
@prateekgogia Yes, that's what i am referring to. Also what I try to make sure with @erikstmartin  is the best practice (which daemonSets dose do support) we want there, and add it to the doc

**Comment by jpds** [comment]
Interestingly, calico appears to be configured to ignore taints completely and so virtual-kubelet keeps trying to schedule its daemonset onto Fargate/other: https://github.com/kubernetes/kubernetes/issues/57120

**Comment by rbitia** [comment]
It seems like Calico now regards taints when scheduling onto nodes. Wondering if it's okay to close the issue?

**Comment by sdanbury** [comment]
@rbitia I can try it out again this week and let you know.

**Comment by corrieb** [comment]
@sdanbury We're housekeeping old issues. Can you update or close the issue? Cheers.

**Comment by sdanbury** [comment]
Yep. I will close and create a new issue when I get round to trying this again. Thanks!

**Comment by cpuguy83** [comment]
Thanks!
