### ISSUE TITLE
Panics with "runtime error: invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by avranju** [virtual-kubelet/virtual-kubelet#29]
When I run `./virtual-kubelet --provider azure` I get this:

```
/home/avranju/.kube/config
2017/12/18 16:17:10 Node 'virtual-kubelet' with OS type 'Linux' registered
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xe9909a]

goroutine 1 [running]:
github.com/virtual-kubelet/virtual-kubelet/manager.(*ResourceManager).incrementRefCounters(0xc4202f59a0, 0xc420077c00)
	/home/avranju/code/go-workspace/src/github.com/virtual-kubelet/virtual-kubelet/manager/resource.go:260 +0xda
github.com/virtual-kubelet/virtual-kubelet/manager.(*ResourceManager).SetPods(0xc4202f59a0, 0xc42029a150)
	/home/avranju/code/go-workspace/src/github.com/virtual-kubelet/virtual-kubelet/manager/resource.go:89 +0x34f
github.com/virtual-kubelet/virtual-kubelet/vkubelet.(*Server).Run(0xc4203bdc80, 0xf, 0x11672e7)
	/home/avranju/code/go-workspace/src/github.com/virtual-kubelet/virtual-kubelet/vkubelet/vkubelet.go:169 +0x2fa
github.com/virtual-kubelet/virtual-kubelet/cmd.glob..func1(0x195e400, 0xc4201d2780, 0x0, 0x2)
	/home/avranju/code/go-workspace/src/github.com/virtual-kubelet/virtual-kubelet/cmd/root.go:54 +0x1cd
github.com/virtual-kubelet/virtual-kubelet/vendor/github.com/spf13/cobra.(*Command).execute(0x195e400, 0xc4200100a0, 0x2, 0x2, 0x195e400, 0xc4200100a0)
	/home/avranju/code/go-workspace/src/github.com/virtual-kubelet/virtual-kubelet/vendor/github.com/spf13/cobra/command.go:702 +0x2c6
github.com/virtual-kubelet/virtual-kubelet/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x195e400, 0x195e620, 0xf31b66, 0x195e540)
	/home/avranju/code/go-workspace/src/github.com/virtual-kubelet/virtual-kubelet/vendor/github.com/spf13/cobra/command.go:783 +0x30e
github.com/virtual-kubelet/virtual-kubelet/vendor/github.com/spf13/cobra.(*Command).Execute(0x195e400, 0x0, 0xc42062bf48)
	/home/avranju/code/go-workspace/src/github.com/virtual-kubelet/virtual-kubelet/vendor/github.com/spf13/cobra/command.go:736 +0x2b
github.com/virtual-kubelet/virtual-kubelet/cmd.Execute()
	/home/avranju/code/go-workspace/src/github.com/virtual-kubelet/virtual-kubelet/cmd/root.go:61 +0x31
main.main()
	/home/avranju/code/go-workspace/src/virtual-kubelet/main.go:20 +0x20
```

I tried fixing `resource.go` to add some `nil` checks in `incrementRefCounters` but that didn't seem to make a difference. I am a _go_ language noob so its probably just my lack of knowledge. Do we know what's going on here? I setup the environment variables for `ACI_REGION`, `ACI_RESOURCE_GROUP` and `AZURE_AUTH_LOCATION` as well. `AZURE_AUTH_LOCATION` points to a file containing this (real values elided below):

```json
{
  "clientId": "...",
  "clientSecret": "...",
  "subscriptionId": "...",
  "tenantId": "..."
}
```

**Comment by rbitia** [comment]
Hi are you still getting this issue?

**Comment by robbiezhang** [comment]
@avranju, can you check which pod is assigned to the virtual-kubelet node, and send us the spec?

**Comment by avranju** [comment]
This issue appears to have been fixed in [this commit](https://github.com/virtual-kubelet/virtual-kubelet/commit/b870ac2eaa1cf79e7db2fdf473df9f66c194c255) now. I think its safe to close this. I am a tad more _go_ lang aware now and was able to patch this and get it to work as well. Thanks!

**Comment by robbiezhang** [comment]
thanks
