### ISSUE TITLE
Can't talk to Service Bus from custom VNET ACI

### ISSUE THREAD

**Issue by AceHack** [virtual-kubelet/virtual-kubelet#445]
When I try to talk to service bus I get the following error but I have another pod running at the same time on a regular AKS node and things work fine.

Microsoft.Azure.ServiceBus.ServiceBusCommunicationException: Resource temporarily unavailable ErrorCode: TryAgain ---> System.Net.Sockets.SocketException: Resource temporarily unavailable
   at Microsoft.Azure.ServiceBus.ServiceBusConnection.CreateConnectionAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.FaultTolerantAmqpObject`1.OnCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.ServiceBus.Amqp.AmqpLinkCreator.CreateAndOpenAmqpLinkAsync()
   at Microsoft.Azure.ServiceBus.Core.MessageSender.CreateLinkAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.FaultTolerantAmqpObject`1.OnCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.ServiceBus.Core.MessageSender.OnSendAsync(IList`1 messageList)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.ServiceBus.Core.MessageSender.OnSendAsync(IList`1 messageList)
   at Microsoft.Azure.ServiceBus.RetryPolicy.RunOperation(Func`1 operation, TimeSpan operationTimeout)
   at Microsoft.Azure.ServiceBus.RetryPolicy.RunOperation(Func`1 operation, TimeSpan operationTimeout)
   at Microsoft.Azure.ServiceBus.Core.MessageSender.SendAsync(IList`1 messageList)
   at Arch.TestService.ServiceBusTest.RunAsync() in /build/src/Arch.TestService/ServiceBusTest.cs:line 173

**Comment by AceHack** [comment]
FYI this appears to be related to DNS, I can curl IP address from inside the pod but DNS does not work.

**Comment by AceHack** [comment]
Following the "new" guide here.
https://docs.microsoft.com/en-us/azure/aks/virtual-nodes-cli
Fixed my DNS issue.

The helm chart way
https://github.com/virtual-kubelet/virtual-kubelet/blob/master/providers/azure/README.md#create-an-aks-cluster-with-vnet
I had the DNS issues above.

Thanks.
