### ISSUE TITLE
OMS add-on in old AKS clusters block virtual node add-on

### ISSUE THREAD

**Issue by rbitia** [virtual-kubelet/virtual-kubelet#455]
---

### Environment summary

Provider (e.g. ACI, AWS Fargate, Hyper)
ACI
Version (e.g. 0.1, 0.2-beta)
latest
K8s Master Info (e.g. AKS, ACS, Bare Metal, EKS)
AKS
Install Method (e.g. Helm Chart, )
virtual node add-on
### Issue Details
If you enable OMS before enabling virtual node as an add-on, and the cluster is "old" you will not be able to install virtual node as an add-on. 
### Repo Steps
Create an AKS cluster with OMS enabled (must be an already created cluster from x months ago) 
Try to install virtual node through the add-on extension in the CLI
Get a nasty bug from OMS

To work around the issue disable the OMS add-on and re-enable it this *should* allow you to enable the virtual node add-on.

**Comment by rbitia** [comment]
https://github.com/Azure/AKS/issues/746

**Comment by dsalamancaMS** [comment]
Did you guys figured it out? Im having the same problem.

```
─ az aks enable-addons -n K8sazurecni -g k8sazurecni --addons virtual-node --subnet-name default
The behavior of this command has been altered by the following extension: aks-virtual-node
'logAnalyticsWorkspaceResourceID'
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.0.52/libexec/lib/python3.7/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.0.52/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 346, in execute
    six.reraise(*sys.exc_info())
  File "/usr/local/Cellar/azure-cli/2.0.52/libexec/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/Cellar/azure-cli/2.0.52/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 320, in execute
    result = cmd(params)
  File "/usr/local/Cellar/azure-cli/2.0.52/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 169, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.52/libexec/lib/python3.7/site-packages/azure/cli/core/__init__.py", line 440, in default_command_handler
    result = op(**command_args)
  File "/Users/dsala/.azure/cliextensions/aks-virtual-node/azext_aksvirtualnode/commands.py", line 47, in enable_addon_override
    _ensure_container_insights_for_monitoring(cmd, instance.addon_profiles['omsagent'])
  File "/usr/local/Cellar/azure-cli/2.0.52/libexec/lib/python3.7/site-packages/azure/cli/command_modules/acs/custom.py", line 1916, in _ensure_container_insights_for_monitoring
    workspace_resource_id = addon.config['logAnalyticsWorkspaceResourceID']
KeyError: 'logAnalyticsWorkspaceResourceID'

```
```
╰─ az extension list
[
  {
    "extensionType": "whl",
    "name": "aks-virtual-node",
    "version": "0.2.0"
  }
]
```

**Comment by srrengar** [comment]
@dsalamancaMS @rbitia  I was not able to repro this by following the doc below to create a cluster but also enable log analytics before virtual node. Can you see if you still face the issue? 

https://docs.microsoft.com/en-us/azure/aks/virtual-nodes-cli

**Comment by ganga1980** [comment]
@dsalamancaMS,  We have fixed this issue in Az CLI in Jan 19. Looks like you are using the old version of the CLI which  has this issue.  Can you please upgrade to latest version of the CLI and try out https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest?

**Comment by srrengar** [comment]
Spoke with Denis and Ganga offline, the new CLI has the fix. @rbitia can you close the issue?
