### ISSUE TITLE
[Hyper] If the config file is not set, hyper provider will crash when pulling images

### ISSUE THREAD

**Issue by arapulido** [virtual-kubelet/virtual-kubelet#46]
The AuthConfig is only set when there is a config file (and the env variables for key and secret are not set), but it is used by ensureImage nevertheless.

Steps to reproduce:

 * Set HYPER_ACCESS_KEY and HYPER_SECRET_KEY env variables
 * Create a pod using an image that you haven't pulled yet

Result:

The Hyper provider crashes:
```
/Users/ara/.kube/config
2017/12/28 11:50:21 Use AccessKey and SecretKey from HYPER_ACCESS_KEY and HYPER_SECRET_KEY
2017/12/28 11:50:21
 Host: tcp://eu-central-1.hyper.sh:443
 AccessKey: 4**********
 SecretKey: 4**********
 InstanceType: s2
2017/12/28 11:50:22 Node 'virtual-kubelet' with OS type 'Linux' registered
2017/12/28 11:50:22 receive GetPods
2017/12/28 11:50:22 found 0 pods
2017/12/28 11:50:37 receive GetPods
2017/12/28 11:50:37 found 0 pods
2017/12/28 11:50:37 Error retrieving pod 'nginx' from provider: Error: No such container: pod-nginx-nginx
2017/12/28 11:50:37 receive CreatePod "nginx"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1b48aa5]

goroutine 1 [running]:
github.com/virtual-kubelet/virtual-kubelet/providers/hypersh.(*HyperProvider).ensureImage(0xc42020d5c0, 0xc42045af80, 0xc, 0x0, 0x0)
	/Users/ara/go/src/github.com/virtual-kubelet/virtual-kubelet/providers/hypersh/util.go:337 +0x105
github.com/virtual-kubelet/virtual-kubelet/providers/hypersh.(*HyperProvider).CreatePod(0xc42020d5c0, 0xc420a0ea80, 0x0, 0x0)
	/Users/ara/go/src/github.com/virtual-kubelet/virtual-kubelet/providers/hypersh/hypersh.go:219 +0x652
github.com/virtual-kubelet/virtual-kubelet/vkubelet.(*Server).createPod(0xc4202104e0, 0xc420a0ea80, 0xc420979a40, 0x2)
	/Users/ara/go/src/github.com/virtual-kubelet/virtual-kubelet/vkubelet/vkubelet.go:274 +0x6d
github.com/virtual-kubelet/virtual-kubelet/vkubelet.(*Server).reconcile(0xc4202104e0)
	/Users/ara/go/src/github.com/virtual-kubelet/virtual-kubelet/vkubelet/vkubelet.go:251 +0x410
github.com/virtual-kubelet/virtual-kubelet/vkubelet.(*Server).Run(0xc4202104e0, 0xf, 0x1dabfb7)
	/Users/ara/go/src/github.com/virtual-kubelet/virtual-kubelet/vkubelet/vkubelet.go:193 +0x449
github.com/virtual-kubelet/virtual-kubelet/cmd.glob..func1(0x25d4a20, 0xc42028d7b0, 0x0, 0x1)
	/Users/ara/go/src/github.com/virtual-kubelet/virtual-kubelet/cmd/root.go:54 +0x1cd
github.com/virtual-kubelet/virtual-kubelet/vendor/github.com/spf13/cobra.(*Command).execute(0x25d4a20, 0xc42000a070, 0x1, 0x1, 0x25d4a20, 0xc42000a070)
	/Users/ara/go/src/github.com/virtual-kubelet/virtual-kubelet/vendor/github.com/spf13/cobra/command.go:702 +0x2c6
github.com/virtual-kubelet/virtual-kubelet/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x25d4a20, 0x25d4c40, 0x1b66736, 0x25d4b60)
	/Users/ara/go/src/github.com/virtual-kubelet/virtual-kubelet/vendor/github.com/spf13/cobra/command.go:783 +0x30e
github.com/virtual-kubelet/virtual-kubelet/vendor/github.com/spf13/cobra.(*Command).Execute(0x25d4a20, 0x0, 0xc42058bf48)
	/Users/ara/go/src/github.com/virtual-kubelet/virtual-kubelet/vendor/github.com/spf13/cobra/command.go:736 +0x2b
github.com/virtual-kubelet/virtual-kubelet/cmd.Execute()
	/Users/ara/go/src/github.com/virtual-kubelet/virtual-kubelet/cmd/root.go:61 +0x31
main.main()```

**Comment by arapulido** [comment]
Closing this issue, as the fix was already merged
