### ISSUE TITLE
mock provider: timed out waiting for client to create streams when exec

### ISSUE THREAD

**Issue by muya-zj** [virtual-kubelet/virtual-kubelet#482]
---

### Environment summary

Provider (e.g. ACI, AWS Fargate, Hyper)

mock

Version (e.g. 0.1, 0.2-beta)

v0.7.3

K8s Master Info (e.g. AKS, ACS, Bare Metal, EKS)

minikube

Install Method (e.g. Helm Chart, )

### Issue Details

when we use kubectl exec ${container_id} xxx，func ExecInContainer of mock provider cannot be called.  The VK output some error log, like

ERROR: logging before flag.Parse: E1220 11:54:40.284366       1 httpstream.go:187] timed out waiting for client to create streams

So I add some print in vendor/k8s.io/kubernetes/pkg/kubelet/server/remotecommand/httpstream.go, I found exec expects 3 streams, that is stdin/stdout/stderr, but actual streams of func waitForStreams are error/stdout/stderr.  Why?

```
// count the streams client asked for, starting with 1
	expectedStreams := 1
	if opts.Stdin {
		expectedStreams++
	}
	if opts.Stdout {
		expectedStreams++
	}
	if opts.Stderr {
		expectedStreams++
	}
	if opts.TTY && handler.supportsTerminalResizing() {
		expectedStreams++
	}
```

```
for {
		select {
		case stream := <-streams:
			streamType := stream.Headers().Get(api.StreamType)
			fmt.Println(streamType)
			switch streamType {
			case api.StreamTypeError:
				ctx.writeStatus = v4WriteStatusFunc(stream) // write json errors
				go waitStreamReply(stream.replySent, replyChan, stop)
			case api.StreamTypeStdin:
				ctx.stdinStream = stream
				go waitStreamReply(stream.replySent, replyChan, stop)
			case api.StreamTypeStdout:
				ctx.stdoutStream = stream
				go waitStreamReply(stream.replySent, replyChan, stop)
			case api.StreamTypeStderr:
				ctx.stderrStream = stream
				go waitStreamReply(stream.replySent, replyChan, stop)
			case api.StreamTypeResize:
				ctx.resizeStream = stream
				go waitStreamReply(stream.replySent, replyChan, stop)
			default:
				runtime.HandleError(fmt.Errorf("Unexpected stream type: %q", streamType))
			}
		case <-replyChan:
			receivedStreams++
			fmt.Println(receivedStreams)
			if receivedStreams == expectedStreams {
				break WaitForStreams
			}
		case <-expired:
			// TODO find a way to return the error to the user. Maybe use a separate
			// stream to report errors?
			return nil, errors.New("timed out waiting for client to create streams")
		}
	}
```
stack:
```
goroutine 3343 [running]:
runtime/debug.Stack(0x0, 0x0, 0xc001176f60)
  /usr/local/go/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
  /usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/virtual-kubelet/virtual-kubelet/vendor/k8s.io/kubernetes/pkg/kubelet/server/remotecommand.createHttpStreamStreams(0xc0011a9600, 0x23468e0, 0xc00097e410, 0xc000b79a5c, 0xc0008f4210, 0x1, 0x1, 0x6fc23ac00, 0x6fc23ac00, 0x0, ...)
  /go/src/github.com/virtual-kubelet/virtual-kubelet/vendor/k8s.io/kubernetes/pkg/kubelet/server/remotecommand/httpstream.go:186 +0x39c
github.com/virtual-kubelet/virtual-kubelet/vendor/k8s.io/kubernetes/pkg/kubelet/server/remotecommand.createStreams(0xc0011a9600, 0x23468e0, 0xc00097e410, 0xc000b79a5c, 0xc0008f4210, 0x1, 0x1, 0x6fc23ac00, 0x6fc23ac00, 0x460aa2, ...)
  /go/src/github.com/virtual-kubelet/virtual-kubelet/vendor/k8s.io/kubernetes/pkg/kubelet/server/remotecommand/httpstream.go:112 +0x1eb
github.com/virtual-kubelet/virtual-kubelet/vendor/k8s.io/kubernetes/pkg/kubelet/server/remotecommand.ServeExec(0x23468e0, 0xc00097e410, 0xc0011a9600, 0x7f64140b8a40, 0xc0007c16c0, 0xc0010dc060, 0x14, 0x0, 0x0, 0xc000385100, ...)
  /go/src/github.com/virtual-kubelet/virtual-kubelet/vendor/k8s.io/kubernetes/pkg/kubelet/server/remotecommand/exec.go:45 +0xab
github.com/virtual-kubelet/virtual-kubelet/vkubelet/api.PodExecHandlerFunc.func1(0x23468e0, 0xc00097e410, 0xc0011a9600)
  /go/src/github.com/virtual-kubelet/virtual-kubelet/vkubelet/api/exec.go:40 +0x416
net/http.HandlerFunc.ServeHTTP(0xc0007d6480, 0x23468e0, 0xc00097e410, 0xc0011a9600)
  /usr/local/go/src/net/http/server.go:1964 +0x44
github.com/virtual-kubelet/virtual-kubelet/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc0002480e0, 0x23468e0, 0xc00097e410, 0xc0011a9600)
  /go/src/github.com/virtual-kubelet/virtual-kubelet/vendor/github.com/gorilla/mux/mux.go:159 +0xf1
github.com/virtual-kubelet/virtual-kubelet/vkubelet.InstrumentHandler.func1(0x23468e0, 0xc00097e410, 0xc0011a9100)
  /go/src/github.com/virtual-kubelet/virtual-kubelet/vkubelet/apiserver.go:79 +0x6f
net/http.HandlerFunc.ServeHTTP(0xc0007d66e0, 0x23468e0, 0xc00097e410, 0xc0011a9100)
  /usr/local/go/src/net/http/server.go:1964 +0x44
github.com/virtual-kubelet/virtual-kubelet/vendor/go.opencensus.io/plugin/ochttp.(*Handler).ServeHTTP(0xc00008b000, 0x23468e0, 0xc00097e410, 0xc0011a8f00)
  /go/src/github.com/virtual-kubelet/virtual-kubelet/vendor/go.opencensus.io/plugin/ochttp/server.go:82 +0x264
net/http.serverHandler.ServeHTTP(0xc00088c000, 0x23455a0, 0xc0008bd6c0, 0xc0011a8f00)
  /usr/local/go/src/net/http/server.go:2741 +0xab
net/http.(*conn).serve(0xc000d57540, 0x2347360, 0xc000c2fb00)
  /usr/local/go/src/net/http/server.go:1847 +0x646
created by net/http.(*Server).Serve
  /usr/local/go/src/net/http/server.go:2851 +0x2f5
ERROR: logging before flag.Parse: E1220 11:54:40.284366       1 httpstream.go:187] timed out waiting for client to create streams
```
### Repo Steps

make skaffold

create a pod on the vk node, then kubectl exec ${container_id} ${command}

**Comment by robbiezhang** [comment]
mock provider hasn't implement the ExecInContainer API.
https://github.com/virtual-kubelet/virtual-kubelet/blob/f7afeba12efee90a20e5b9d0b6ff49eeca6969fa/providers/mock/mock.go#L214-L219

**Comment by muya-zj** [comment]
> mock provider hasn't implement the ExecInContainer API.
> [virtual-kubelet/providers/mock/mock.go](https://github.com/virtual-kubelet/virtual-kubelet/blob/f7afeba12efee90a20e5b9d0b6ff49eeca6969fa/providers/mock/mock.go#L214-L219)
> 
> Lines 214 to 219 in [f7afeba](/virtual-kubelet/virtual-kubelet/commit/f7afeba12efee90a20e5b9d0b6ff49eeca6969fa)
> 
>  // ExecInContainer executes a command in a container in the pod, copying data 
>  // between in/out/err and the container's stdin/stdout/stderr. 
>  func (p *MockProvider) ExecInContainer(name string, uid types.UID, container string, cmd []string, in io.Reader, out, err io.WriteCloser, tty bool, resize <-chan remotecommand.TerminalSize, timeout time.Duration) error { 
>  	log.Printf("receive ExecInContainer %q\n", container) 
>  	return nil 
>  }

As I understand, although this function is not implemented, it should be triggered and output log printf when kubectl exec. Actually, errors occur before func ExecInContainer is called.

**Comment by muya-zj** [comment]
ping @cpuguy83

**Comment by cpuguy83** [comment]
If it's stuck in `createStreams` as the stack seems to indicate, then it seems like there is some issue negotiating the http stream.

I'm really not familiar with `remotecommand`, but it seems like you should be able to reproduce with just that library and not VK at all.

**Comment by muya-zj** [comment]
> If it's stuck in `createStreams` as the stack seems to indicate, then it seems like there is some issue negotiating the http stream.
> 
> I'm really not familiar with `remotecommand`, but it seems like you should be able to reproduce with just that library and not VK at all.

I find the solution as follows,
```sh
diff --git a/vkubelet/api/exec.go b/vkubelet/api/exec.go
index c5281644..75ff0b04 100644
--- a/vkubelet/api/exec.go
+++ b/vkubelet/api/exec.go
@@ -3,6 +3,7 @@ package api
 import (
        "fmt"
        "net/http"
+       "net/url"
        "strings"
        "time"

@@ -28,10 +29,10 @@ func PodExecHandlerFunc(backend remotecommand.Executor) http.HandlerFunc {

                // TODO: tty flag causes remotecommand.createStreams to wait for the wrong number of streams
                streamOpts := &remotecommand.Options{
-                       Stdin:  true,
-                       Stdout: true,
-                       Stderr: true,
-                       TTY:    false,
+                       Stdin:  OptionCheck(q, "input"),
+                       Stdout: OptionCheck(q, "output"),
+                       Stderr: OptionCheck(q, "error"),
+                       TTY:    OptionCheck(q, "tty"),
                }

                idleTimeout := time.Second * 30
@@ -40,3 +41,11 @@ func PodExecHandlerFunc(backend remotecommand.Executor) http.HandlerFunc {
                remotecommand.ServeExec(w, req, backend, fmt.Sprintf("%s-%s", namespace, pod), "", container, command, streamOpts, idleTimeout, streamCreationTimeout, supportedStreamProtocols)
        }
 }
+
+// OptionCheck checks the option with req.URL.Query().
+func OptionCheck(v url.Values, option string) bool {
+       if _, ok := v[option]; ok {
+               return true
+       }
+       return false
+}
```

**Comment by cpuguy83** [comment]
@muya-zj That makes sense. Did you want to open a PR?
I assume kubectl is sending these values?
