### ISSUE TITLE
Http add-on doesn't install correctly 

### ISSUE THREAD

**Issue by rbitia** [virtual-kubelet/virtual-kubelet#490]
---

### Environment summary

Provider (e.g. ACI, AWS Fargate, Hyper)
ACI
Version (e.g. 0.1, 0.2-beta)

K8s Master Info (e.g. AKS, ACS, Bare Metal, EKS)
AKS
Install Method (e.g. Helm Chart, )
virtual node portal experience 

### Issue Details
MININT-04PTR80:labs riabhatia$ az aks enable-addons --resource-group kubecon-seattle --name kubecon-user1  --addons http_application_routing
The behavior of this command has been altered by the following extension: aks-virtual-node
local variable 'os_type' referenced before assignment
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.0.44/libexec/lib/python3.7/site-packages/knack/cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.0.44/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 369, in execute
    six.reraise(*sys.exc_info())
  File "/usr/local/Cellar/azure-cli/2.0.44/libexec/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/Cellar/azure-cli/2.0.44/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 343, in execute
    result = cmd(params)
  File "/usr/local/Cellar/azure-cli/2.0.44/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 182, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.44/libexec/lib/python3.7/site-packages/azure/cli/core/__init__.py", line 436, in default_command_handler
    result = op(**command_args)
  File "/Users/riabhatia/.azure/cliextensions/aks-virtual-node/azext_aksvirtualnode/commands.py", line 41, in enable_addon_override
    workspace_resource_id=workspace_resource_id, subnet_name=subnet_name, no_wait=no_wait)
  File "/Users/riabhatia/.azure/cliextensions/aks-virtual-node/azext_aksvirtualnode/commands.py", line 100, in _update_addons_extension
    elif addon == 'aciConnector'+os_type:
UnboundLocalError: local variable 'os_type' referenced before assignment
### Repo Steps
create an AKS cluster with the virtual node installed on it
enable the http application routing add on with : az aks enable-addons --resource-group kubecon-seattle --name kubecon-user1  --addons http_application_routing

**Comment by jeremyrickard** [comment]
Hey @rbitia check your extension version:

```
az extension list
```

This should have been fixed in the 0.2.0 release of the extension. It's also worth noting that it would be beneficial to try this out with the new AZ extension. 

On a related note, we should maybe track this outside the VK github org since it's azure cli specific.

**Comment by rbitia** [comment]
Moved to AKS issues: https://github.com/Azure/AKS/issues/777

**Comment by rbitia** [comment]
Closing the issue here!
