### ISSUE TITLE
SFMesh panics when built off master branch

### ISSUE THREAD

**Issue by sylus** [virtual-kubelet/virtual-kubelet#512]
### Environment summary

Provider (e.g. ACI, AWS Fargate, Hyper): sfmesh

Version (e.g. 0.1, 0.2-beta): master

K8s Master Info (e.g. AKS, ACS, Bare Metal, EKS): Docker for Mac

Install Method (e.g. Helm Chart, ): Master build

### Issue Details

I got virtual kubelet working on my local docker-for-mac k8s cluster using ACI, but also wanted to try sfmesh but seems to panic. I checked i have all the envvar properly exported. Was curious whether this doesn’t work yet but was told in Slack to file an issue?

### Repo Steps

```sh
./bin/virtual-kubelet --provider sfmesh

ERRO[0000] TLS certificates not provided, not setting up pod http server  certPath= keyPath= namespace= node=test operatingSystem=Linux provider=sfmesh
INFO[0000] Registered node                               namespace= node=test operatingSystem=Linux provider=sfmesh
2019/01/23 23:03:35 receive GetPods
INFO[0000] starting workers                              namespace= node=test operatingSystem=Linux provider=sfmesh
INFO[0000] started workers                               namespace= node=test operatingSystem=Linux provider=sfmesh
2019/01/23 23:03:36 receive GetPod "kube-proxy-kprwb"
2019/01/23 23:03:36 receive CreatePod "kube-proxy-kprwb"
E0123 23:03:36.140464   86093 runtime.go:69] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error:invalid memory address or nil pointer dereference)
/Users/sylus/go/src/github.com/virtual-kubelet/virtual-kubelet/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:76
/Users/sylus/go/src/github.com/virtual-kubelet/virtual-kubelet/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/Users/sylus/go/src/github.com/virtual-kubelet/virtual-kubelet/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/local/Cellar/go/1.11.2/libexec/src/runtime/asm_amd64.s:522
/usr/local/Cellar/go/1.11.2/libexec/src/runtime/panic.go:513
/usr/local/Cellar/go/1.11.2/libexec/src/runtime/panic.go:82
/usr/local/Cellar/go/1.11.2/libexec/src/runtime/signal_unix.go:390
/Users/sylus/go/src/github.com/virtual-kubelet/virtual-kubelet/providers/sfmesh/sfmesh.go:369
/Users/sylus/go/src/github.com/virtual-kubelet/virtual-kubelet/providers/sfmesh/sfmesh.go:415
/Users/sylus/go/src/github.com/virtual-kubelet/virtual-kubelet/vkubelet/pod.go:52
/Users/sylus/go/src/github.com/virtual-kubelet/virtual-kubelet/vkubelet/podcontroller.go:286
/Users/sylus/go/src/github.com/virtual-kubelet/virtual-kubelet/vkubelet/podcontroller.go:257
/Users/sylus/go/src/github.com/virtual-kubelet/virtual-kubelet/vkubelet/podcontroller.go:195
/Users/sylus/go/src/github.com/virtual-kubelet/virtual-kubelet/vkubelet/podcontroller.go:209
/Users/sylus/go/src/github.com/virtual-kubelet/virtual-kubelet/vkubelet/podcontroller.go:155
/Users/sylus/go/src/github.com/virtual-kubelet/virtual-kubelet/vkubelet/podcontroller.go:142
/Users/sylus/go/src/github.com/virtual-kubelet/virtual-kubelet/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133
/Users/sylus/go/src/github.com/virtual-kubelet/virtual-kubelet/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134
/Users/sylus/go/src/github.com/virtual-kubelet/virtual-kubelet/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
/usr/local/Cellar/go/1.11.2/libexec/src/runtime/asm_amd64.s:1333
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x226d3d2]

goroutine 126 [running]:
github.com/virtual-kubelet/virtual-kubelet/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /Users/sylus/go/src/github.com/virtual-kubelet/virtual-kubelet/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x108
panic(0x2485000, 0x3a343a0)
        /usr/local/Cellar/go/1.11.2/libexec/src/runtime/panic.go:513 +0x1b9
github.com/virtual-kubelet/virtual-kubelet/providers/sfmesh.(*SFMeshProvider).getMeshNetwork(0xc0003206c0, 0xc000736380, 0x0, 0xc000262cc0, 0xc0002342d0, 0x0, 0xc0007363a0, 0x0, 0xc000320710, 0xc0000420a7, ...)
        /Users/sylus/go/src/github.com/virtual-kubelet/virtual-kubelet/providers/sfmesh/sfmesh.go:369 +0x262
github.com/virtual-kubelet/virtual-kubelet/providers/sfmesh.(*SFMeshProvider).CreatePod(0xc0003206c0, 0x2991a20, 0xc000234030, 0xc000736380, 0xc00062a1b0, 0xc0005b8690)
        /Users/sylus/go/src/github.com/virtual-kubelet/virtual-kubelet/providers/sfmesh/sfmesh.go:415 +0x1e2
github.com/virtual-kubelet/virtual-kubelet/vkubelet.(*Server).createOrUpdatePod(0xc000229ce0, 0x2991a20, 0xc000234030, 0xc000736380, 0x29923e0, 0xc000299300, 0x0, 0x0)
        /Users/sylus/go/src/github.com/virtual-kubelet/virtual-kubelet/vkubelet/pod.go:52 +0x337
github.com/virtual-kubelet/virtual-kubelet/vkubelet.(*PodController).syncPodInProvider(0xc000038a00, 0x2991a20, 0xc0002e08a0, 0xc000736380, 0x0, 0x0)
        /Users/sylus/go/src/github.com/virtual-kubelet/virtual-kubelet/vkubelet/podcontroller.go:286 +0x2d6
github.com/virtual-kubelet/virtual-kubelet/vkubelet.(*PodController).syncHandler(0xc000038a00, 0x2991a20, 0xc0002e07b0, 0xc0005bd180, 0x1c, 0x0, 0x0)
        /Users/sylus/go/src/github.com/virtual-kubelet/virtual-kubelet/vkubelet/podcontroller.go:257 +0x748
github.com/virtual-kubelet/virtual-kubelet/vkubelet.(*PodController).processNextWorkItem.func1(0xc000038a00, 0x2991a20, 0xc0002e0720, 0xc0005e0600, 0x23d28a0, 0xc00063e370, 0x0, 0x0)
        /Users/sylus/go/src/github.com/virtual-kubelet/virtual-kubelet/vkubelet/podcontroller.go:195 +0x1af
github.com/virtual-kubelet/virtual-kubelet/vkubelet.(*PodController).processNextWorkItem(0xc000038a00, 0x2991a20, 0xc0002e0720, 0x2791bdb, 0x2, 0x0)
        /Users/sylus/go/src/github.com/virtual-kubelet/virtual-kubelet/vkubelet/podcontroller.go:209 +0x20b
github.com/virtual-kubelet/virtual-kubelet/vkubelet.(*PodController).runWorker(0xc000038a00, 0x2991960, 0xc0002989c0, 0x2791bdb, 0x2)
        /Users/sylus/go/src/github.com/virtual-kubelet/virtual-kubelet/vkubelet/podcontroller.go:155 +0x53
github.com/virtual-kubelet/virtual-kubelet/vkubelet.(*PodController).Run.func1()
        /Users/sylus/go/src/github.com/virtual-kubelet/virtual-kubelet/vkubelet/podcontroller.go:142 +0x7e
github.com/virtual-kubelet/virtual-kubelet/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc000370e10)
        /Users/sylus/go/src/github.com/virtual-kubelet/virtual-kubelet/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x54
github.com/virtual-kubelet/virtual-kubelet/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000370e10, 0x3b9aca00, 0x0, 0x1, 0xc0002ba3c0)
        /Users/sylus/go/src/github.com/virtual-kubelet/virtual-kubelet/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xbe
github.com/virtual-kubelet/virtual-kubelet/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc000370e10, 0x3b9aca00, 0xc0002ba3c0)
        /Users/sylus/go/src/github.com/virtual-kubelet/virtual-kubelet/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by github.com/virtual-kubelet/virtual-kubelet/vkubelet.(*PodController).Run
        /Users/sylus/go/src/github.com/virtual-kubelet/virtual-kubelet/vkubelet/podcontroller.go:140 +0x223
```

**Comment by rbitia** [comment]
@dkkapur if you have a chance here's something to take a look at.

**Comment by srrengar** [comment]
@yaron2 can you take a look at this

**Comment by yaron2** [comment]
@srrengar The SF Mesh ARM spec has changed a few months back in a non-backward compatible way.
This effectively means most of the provider needs to be re-written.

**Comment by srrengar** [comment]
@yaron2 thanks for letting us know. Can we remove this provider if it will not be rewritten? 

+ @rbitia

**Comment by yaron2** [comment]
Yes, I actually don't see a reason to re-write it unless someone knows about concrete uses for it.

**Comment by cpuguy83** [comment]
FYI, sfmesh was removed from the providers
