### ISSUE TITLE
[Azure] VK crashing 

### ISSUE THREAD

**Issue by rbitia** [virtual-kubelet/virtual-kubelet#63]
Installed the connector last week and now it's crashing:

goroutine 1 [running]:
github.com/virtual-kubelet/virtual-kubelet/manager.(*ResourceManager).incrementRefCounters(0xc42005dea0, 0xc42024d180)
        /go/src/github.com/virtual-kubelet/virtual-kubelet/manager/resource.go:260 +0xda
github.com/virtual-kubelet/virtual-kubelet/manager.(*ResourceManager).SetPods(0xc42005dea0, 0xc42031c380)
        /go/src/github.com/virtual-kubelet/virtual-kubelet/manager/resource.go:89 +0x34f
github.com/virtual-kubelet/virtual-kubelet/vkubelet.(*Server).Run(0xc4200426c0, 0x22, 0x7ffe15c38b13)
        /go/src/github.com/virtual-kubelet/virtual-kubelet/vkubelet/vkubelet.go:169 +0x2fa
github.com/virtual-kubelet/virtual-kubelet/cmd.glob..func1(0x194a040, 0xc42014c600, 0x0, 0x8)
        /go/src/github.com/virtual-kubelet/virtual-kubelet/cmd/root.go:54 +0x1cd
github.com/virtual-kubelet/virtual-kubelet/vendor/github.com/spf13/cobra.(*Command).execute(0x194a040, 0xc42000e0a0, 0x8, 0x8, 0x194a040, 0xc42000e0a0)
        /go/src/github.com/virtual-kubelet/virtual-kubelet/vendor/github.com/spf13/cobra/command.go:702 +0x2c6
github.com/virtual-kubelet/virtual-kubelet/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x194a040, 0x194a260, 0xc42006e3c0, 0x194a180)
        /go/src/github.com/virtual-kubelet/virtual-kubelet/vendor/github.com/spf13/cobra/command.go:783 +0x30e
github.com/virtual-kubelet/virtual-kubelet/vendor/github.com/spf13/cobra.(*Command).Execute(0x194a040, 0x0, 0xc4205b5f48)
        /go/src/github.com/virtual-kubelet/virtual-kubelet/vendor/github.com/spf13/cobra/command.go:736 +0x2b
github.com/virtual-kubelet/virtual-kubelet/cmd.Execute()
        /go/src/github.com/virtual-kubelet/virtual-kubelet/cmd/root.go:61 +0x31
main.main()
        /go/src/github.com/virtual-kubelet/virtual-kubelet/main.go:20 +0x20

**Comment by rbitia** [comment]
#65 fixes this. 
Check out the azure provider readme to update the virtual kubelet docker image to be able to use empty dir w/ ACI. Closing for now since I've verified the fix.
