### ISSUE TITLE
Comparison of Pod resource limits panics

### ISSUE THREAD

**Issue by gabrielhartmann** [virtual-kubelet/virtual-kubelet#753]
---

### Environment summary

Provider (e.g. ACI, AWS Fargate): On prem

Version (e.g. 0.1, 0.2-beta): 1.0 (master/9443e32ae7bf5aa3ec4b970cc8ed6df25ba039cf)

K8s Master Info (e.g. AKS, ACS, Bare Metal, EKS): Bare Metal

Install Method (e.g. Helm Chart, ): Custom

### Issue Details
Here's the stack trace:
```
[66760]: /usr/local/go/src/runtime/asm_amd64.s:1337
[66760]: panic: cannot handle unexported field: {[]v1.Container}[0].Resources.Limits["cpu"].i
[66760]: consider using a custom Comparer; if you control the implementation of type, you can also consider AllowUnexported or cmpopts.IgnoreUnexported [recovered]
[66760]:         panic: cannot handle unexported field: {[]v1.Container}[0].Resources.Limits["cpu"].i
[66760]: consider using a custom Comparer; if you control the implementation of type, you can also consider AllowUnexported or cmpopts.IgnoreUnexported
[66760]: goroutine 275 [running]:
[66760]: k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
[66760]:         /Users/ghartmann/code/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190404173353-6a84e37a896d/pkg/util/runtime/runtime.go:58 +0x105
[66760]: panic(0x12ce480, 0xc000b5a7b0)
[66760]:         /usr/local/go/src/runtime/panic.go:522 +0x1b5
[66760]: github.com/google/go-cmp/cmp.validator.apply(0xc000b59600, 0x144ef60, 0xc0004b6c40, 0xb9, 0x144ef60, 0xc0004b6c80, 0xb9)
[66760]:         /Users/ghartmann/code/go/pkg/mod/github.com/google/go-cmp@v0.3.1/cmp/options.go:229 +0x15b
[66760]: github.com/google/go-cmp/cmp.(*state).tryOptions(0xc000b59600, 0x1732a80, 0x144ef60, 0x144ef60, 0xc0004b6c40, 0xb9, 0x144ef60, 0xc0004b6c80, 0xb9, 0x1)
[66760]:         /Users/ghartmann/code/go/pkg/mod/github.com/google/go-cmp@v0.3.1/cmp/compare.go:269 +0x129
[66760]: github.com/google/go-cmp/cmp.(*state).compareAny(0xc000b59600, 0x16f57c0, 0xc00033c600)
[66760]:         /Users/ghartmann/code/go/pkg/mod/github.com/google/go-cmp@v0.3.1/cmp/compare.go:224 +0x27e
[66760]: github.com/google/go-cmp/cmp.(*state).compareStruct(0xc000b59600, 0x1732a80, 0x1448c20, 0x1448c20, 0xc0004b6c40, 0x99, 0x1448c20, 0xc0004b6c80, 0x99)
[66760]:         /Users/ghartmann/code/go/pkg/mod/github.com/google/go-cmp@v0.3.1/cmp/compare.go:383 +0x581
[66760]: github.com/google/go-cmp/cmp.(*state).compareAny(0xc000b59600, 0x16f5740, 0xc0009f71a0)
[66760]:         /Users/ghartmann/code/go/pkg/mod/github.com/google/go-cmp@v0.3.1/cmp/compare.go:252 +0x100d
[66760]: github.com/google/go-cmp/cmp.(*state).compareMap(0xc000b59600, 0x1732a80, 0x13807c0, 0x13807c0, 0xc0001c34a8, 0x195, 0x13807c0, 0xc000b9c6e8, 0x195)
[66760]:         /Users/ghartmann/code/go/pkg/mod/github.com/google/go-cmp@v0.3.1/cmp/compare.go:500 +0x3de
[66760]: github.com/google/go-cmp/cmp.(*state).compareAny(0xc000b59600, 0x16f57c0, 0xc00033c500)
[66760]:         /Users/ghartmann/code/go/pkg/mod/github.com/google/go-cmp@v0.3.1/cmp/compare.go:256 +0xe35
[66760]: github.com/google/go-cmp/cmp.(*state).compareStruct(0xc000b59600, 0x1732a80, 0x13bcfc0, 0x13bcfc0, 0xc0001c34a8, 0x199, 0x13bcfc0, 0xc000b9c6e8, 0x199)
[66760]:         /Users/ghartmann/code/go/pkg/mod/github.com/google/go-cmp@v0.3.1/cmp/compare.go:383 +0x581
[66760]: github.com/google/go-cmp/cmp.(*state).compareAny(0xc000b59600, 0x16f57c0, 0xc0009fcf00)
[66760]:         /Users/ghartmann/code/go/pkg/mod/github.com/google/go-cmp@v0.3.1/cmp/compare.go:252 +0x100d
[66760]: github.com/google/go-cmp/cmp.(*state).compareStruct(0xc000b59600, 0x1732a80, 0x1499ea0, 0x1499ea0, 0xc0001c3400, 0x199, 0x1499ea0, 0xc000b9c640, 0x199)
[66760]:         /Users/ghartmann/code/go/pkg/mod/github.com/google/go-cmp@v0.3.1/cmp/compare.go:383 +0x581
[66760]: github.com/google/go-cmp/cmp.(*state).compareAny(0xc000b59600, 0x16f5780, 0xc000196960)
[66760]:         /Users/ghartmann/code/go/pkg/mod/github.com/google/go-cmp@v0.3.1/cmp/compare.go:252 +0x100d
[66760]: github.com/google/go-cmp/cmp.(*state).statelessCompare(0xc000b59600, 0x16f5780, 0xc000196960, 0x12ca180, 0xc000abb401)
[66760]:         /Users/ghartmann/code/go/pkg/mod/github.com/google/go-cmp@v0.3.1/cmp/compare.go:203 +0x97
[66760]: github.com/google/go-cmp/cmp.(*state).compareSlice.func2(0x0, 0x0, 0x0, 0x229d880)
[66760]:         /Users/ghartmann/code/go/pkg/mod/github.com/google/go-cmp@v0.3.1/cmp/compare.go:437 +0x7f
[66760]: github.com/google/go-cmp/cmp/internal/diff.Difference(0x1, 0x1, 0xc000455658, 0x1, 0x1, 0xc0004c7ec0)
[66760]:         /Users/ghartmann/code/go/pkg/mod/github.com/google/go-cmp@v0.3.1/cmp/internal/diff/diff.go:221 +0x227
[66760]: github.com/google/go-cmp/cmp.(*state).compareSlice(0xc000b59600, 0x1732a80, 0x1294ec0, 0x1294ec0, 0xc000b86700, 0x97, 0x1294ec0, 0xc000b86720, 0x97)
[66760]:         /Users/ghartmann/code/go/pkg/mod/github.com/google/go-cmp@v0.3.1/cmp/compare.go:436 +0x70d
[66760]: github.com/google/go-cmp/cmp.(*state).compareAny(0xc000b59600, 0x16e8d00, 0xc0004b6a80)
[66760]:         /Users/ghartmann/code/go/pkg/mod/github.com/google/go-cmp@v0.3.1/cmp/compare.go:254 +0xab9
[66760]: github.com/google/go-cmp/cmp.Equal(0x1294ec0, 0xc000b86700, 0x1294ec0, 0xc000b86720, 0x0, 0x0, 0x0, 0x12ce480)
[66760]:         /Users/ghartmann/code/go/pkg/mod/github.com/google/go-cmp@v0.3.1/cmp/compare.go:107 +0x3b7
[66760]: github.com/virtual-kubelet/virtual-kubelet/node.podsEqual(0xc000431180, 0xc000d67180, 0xc000b76e70)
[66760]:         /Users/ghartmann/code/virtual-kubelet/virtual-kubelet/node/pod.go:106 +0xb5
[66760]: github.com/virtual-kubelet/virtual-kubelet/node.(*PodController).createOrUpdatePod(0xc000a130a0, 0x16f9680, 0xc000b76e70, 0xc000d66700, 0x0, 0x0)
[66760]:         /Users/ghartmann/code/virtual-kubelet/virtual-kubelet/node/pod.go:76 +0x3d4
[66760]: github.com/virtual-kubelet/virtual-kubelet/node.(*PodController).syncPodInProvider(0xc000a130a0, 0x16f9680, 0xc000b76e10, 0xc000d66700, 0x0, 0x0)
[66760]:         /Users/ghartmann/code/virtual-kubelet/virtual-kubelet/node/podcontroller.go:345 +0x33f
[66760]: github.com/virtual-kubelet/virtual-kubelet/node.(*PodController).syncHandler(0xc000a130a0, 0x16f9680, 0xc000b76de0, 0xc0009cd260, 0x2c, 0x0, 0x0)
[66760]:         /Users/ghartmann/code/virtual-kubelet/virtual-kubelet/node/podcontroller.go:316 +0x78f
[66760]: github.com/virtual-kubelet/virtual-kubelet/node.handleQueueItem.func1(0xc000455d98, 0x171b860, 0xc000463f60, 0x1702240, 0x229d880, 0xc0004dddf0, 0x12ce480, 0xc000da1b90, 0x0, 0x0)
[66760]:         /Users/ghartmann/code/virtual-kubelet/virtual-kubelet/node/queue.go:69 +0x22f
[66760]: github.com/virtual-kubelet/virtual-kubelet/node.handleQueueItem(0x16f9680, 0xc000b76db0, 0x171b860, 0xc000463f60, 0xc0004dddf0, 0x12ce400)
[66760]:         /Users/ghartmann/code/virtual-kubelet/virtual-kubelet/node/queue.go:83 +0x1f6
[66760]: github.com/virtual-kubelet/virtual-kubelet/node.(*PodController).processNextWorkItem(0xc000a130a0, 0x16f9680, 0xc000b76d80, 0x14eb628, 0x1, 0x171b860, 0xc000463f60, 0x0)
[66760]:         /Users/ghartmann/code/virtual-kubelet/virtual-kubelet/node/podcontroller.go:277 +0x17f
[66760]: github.com/virtual-kubelet/virtual-kubelet/node.(*PodController).runWorker(0xc000a130a0, 0x16f9680, 0xc000578990, 0x14eb628, 0x1, 0x171b860, 0xc000463f60)
[66760]:         /Users/ghartmann/code/virtual-kubelet/virtual-kubelet/node/podcontroller.go:264 +0x6a
[66760]: github.com/virtual-kubelet/virtual-kubelet/node.(*PodController).Run.func1()
[66760]:         /Users/ghartmann/code/virtual-kubelet/virtual-kubelet/node/podcontroller.go:242 +0x60
[66760]: k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc000b76d50)
[66760]:         /Users/ghartmann/code/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190404173353-6a84e37a896d/pkg/util/wait/wait.go:152 +0x54
[66760]: k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000b76d50, 0x3b9aca00, 0x0, 0x1, 0xc00002ad80)
[66760]:         /Users/ghartmann/code/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190404173353-6a84e37a896d/pkg/util/wait/wait.go:153 +0xf8
[66760]: k8s.io/apimachinery/pkg/util/wait.Until(0xc000b76d50, 0x3b9aca00, 0xc00002ad80)
[66760]:         /Users/ghartmann/code/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190404173353-6a84e37a896d/pkg/util/wait/wait.go:88 +0x4d
[66760]: created by github.com/virtual-kubelet/virtual-kubelet/node.(*PodController).Run
[66760]:         /Users/ghartmann/code/virtual-kubelet/virtual-kubelet/node/podcontroller.go:240 +0x5af
```

### Repo Steps
Start a pod controller.

**Comment by sargun** [comment]
This appears to be from dependency versioning problems.

**Comment by Icedroid** [comment]
I meeted the same probelm.  @sargun How to solve?
